[package]
name = "bf"
version = "0.1.0"
authors = ["Romulus Pasca <romulus.pasca@trucknet.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
